# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import numpy
import numpy.typing
import typing

@typing.final
class Argument:
    r"""
    A named register argument (e.g., `q[0]`, `c[2]`) used by high-level instructions.
    """
    @property
    def regid(self) -> builtins.str: ...
    @regid.setter
    def regid(self, value: builtins.str) -> None: ...
    @property
    def index(self) -> builtins.int: ...
    @index.setter
    def index(self, value: builtins.int) -> None: ...
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def __new__(cls, regid:builtins.str, index:builtins.int) -> Argument:
        r"""
        Creates a register argument like `("q", 0)`.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Circ:
    r"""
    Circuit with an explicit trailing qubit permutation.
    """
    @property
    def instrs(self) -> builtins.list[Instr]: ...
    @property
    def perm(self) -> builtins.list[builtins.int]: ...
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __lt__(self, other:builtins.object) -> builtins.bool: ...
    def __le__(self, other:builtins.object) -> builtins.bool: ...
    def __gt__(self, other:builtins.object) -> builtins.bool: ...
    def __ge__(self, other:builtins.object) -> builtins.bool: ...
    def __new__(cls, instrs:typing.Sequence[Instr], perm:typing.Optional[builtins.list[builtins.int]]=None) -> Circ:
        r"""
        Creates a circuit from instructions and an optional permutation.
        """
    def nqubits(self) -> builtins.int:
        r"""
        Number of qubits tracked by the permutation.
        """
    def rotate_representative(self) -> IdentityCirc:
        r"""
        Returns canonical identity representative across rotations/permutations.
        """
    def representative(self) -> Circ:
        r"""
        Returns canonical circuit representative.
        """
    def representative_with_perm(self) -> tuple[Circ, builtins.list[builtins.int]]:
        r"""
        Returns `(representative, applied_perm)` used in canonicalization.
        """
    def permut(self, perm:builtins.list[builtins.int]) -> Circ:
        r"""
        Applies a qubit permutation to this circuit.
        """
    def remove_swaps(self) -> Circ:
        r"""
        Removes explicit swap gates into the stored trailing permutation.
        """
    def inverse(self) -> Circ:
        r"""
        Returns inverse circuit.
        """
    def rotate(self, n:builtins.int) -> Circ:
        r"""
        Circularly rotates instruction order by `n`.
        """
    def len(self) -> builtins.int:
        r"""
        Number of instructions.
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Returns whether the circuit is empty.
        """
    def instrs_with_swaps(self) -> builtins.list[Instr]:
        r"""
        Returns instructions plus swaps needed for stored permutation.
        """
    def __add__(self, other:Circ) -> Circ: ...
    def __len__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __hash__(self) -> builtins.int: ...
    def __getitem__(self, idx:builtins.int) -> Instr: ...

@typing.final
class ECC:
    r"""
    One equivalence class of circuits.
    """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def circuits(self) -> builtins.list[builtins.list[Instr]]:
        r"""
        Returns all circuits in this class with swap instructions materialized.
        """

@typing.final
class ECCs:
    r"""
    Collection of equivalence classes for a fixed number of qubits.
    """
    @property
    def nqubits(self) -> builtins.int: ...
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def dump_quartz(self, filepath:builtins.str) -> None:
        r"""
        Exports ECCs to Quartz JSON format.
        """
    @staticmethod
    def from_postcard(filepath:builtins.str) -> ECCs:
        r"""
        Loads ECCs from a postcard file.
        """
    def dump_postcard(self, filepath:builtins.str) -> None:
        r"""
        Saves ECCs as postcard.
        """
    def check(self) -> builtins.list[ECC]:
        r"""
        Returns classes that fail randomized equivalence checks.
        """
    def __len__(self) -> builtins.int: ...
    def to_list(self) -> builtins.list[ECC]:
        r"""
        Returns all classes as a Python list.
        """
    def filter_single(self) -> ECCs:
        r"""
        Removes classes with only one circuit.
        """
    def to_identity_circuits(self) -> builtins.list[tuple[IdentityCirc, Circ, Circ]]:
        r"""
        Converts classes into canonical identities plus witness circuit pairs.
        """

@typing.final
class Evaluator:
    r"""
    Randomized evaluator used to hash circuits and recover permutation metadata.
    """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __new__(cls, nqubits:builtins.int) -> Evaluator:
        r"""
        Creates a random evaluator for `nqubits`.
        """
    def nqubits(self) -> builtins.int:
        r"""
        Returns evaluator qubit count.
        """
    def evaluate(self, instrs:typing.Sequence[Instr]) -> tuple[StateVec, builtins.list[builtins.int], builtins.list[builtins.int], StateVec]:
        r"""
        Python wrapper for circuit evaluation.
        """
    def initial_key(self) -> builtins.int:
        r"""
        Hash key for the empty circuit under this evaluator.
        """

@typing.final
class Gate:
    r"""
    Parameterized quantum gate definition used by both search and Python APIs.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Gate name.
        """
    @property
    def params(self) -> builtins.list[builtins.str]:
        r"""
        Symbolic parameter list.
        """
    @property
    def params_f(self) -> builtins.list[builtins.float]:
        r"""
        Numeric parameters evaluated with support for `pi` expressions.
        """
    @property
    def matrix(self) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Dense unitary matrix.
        """
    @property
    def nqargs(self) -> builtins.int:
        r"""
        Number of qubit arguments required by this gate.
        """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    @staticmethod
    def from_name(name:builtins.str) -> typing.Optional[Gate]:
        r"""
        Looks up a built-in gate by display name.
        """
    def adjoint(self) -> Gate:
        r"""
        Returns the adjoint (inverse) gate.
        """
    def __call__(self, *args) -> typing.Union[Instr, Instruction]:
        r"""
        Binds arguments and returns either compact `Instr` (integer qargs)
        or high-level `Instruction` (register-style args).
        """

@typing.final
class IdentityCirc:
    r"""
    Canonical identity circuit (a circuit proven equivalent to identity).
    """
    @property
    def inner(self) -> Circ:
        r"""
        Underlying circuit representation.
        """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __lt__(self, other:builtins.object) -> builtins.bool: ...
    def __le__(self, other:builtins.object) -> builtins.bool: ...
    def __gt__(self, other:builtins.object) -> builtins.bool: ...
    def __ge__(self, other:builtins.object) -> builtins.bool: ...
    def __new__(cls, circuit:Circ) -> IdentityCirc:
        r"""
        Creates an identity circuit and checks it is semantically valid.
        """
    @staticmethod
    def from_python(obj:typing.Any) -> IdentityCirc:
        r"""
        Parses a Python-serialized identity object.
        """
    def nqubits(self) -> builtins.int:
        r"""
        Returns number of qubits.
        """
    def qargs_forward(self, gate_id:builtins.int) -> builtins.list[builtins.int]:
        r"""
        For each argument of gate `gate_id`, returns next gate index using that qubit.
        """
    def qargs_backward(self, gate_id:builtins.int) -> builtins.list[builtins.int]:
        r"""
        For each argument of gate `gate_id`, returns previous gate index using that qubit.
        """
    def check(self) -> builtins.bool:
        r"""
        Randomized semantic check that this circuit is identity.
        """
    def hash_value(self) -> builtins.int:
        r"""
        Stable hash of the canonical identity representation.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __hash__(self) -> builtins.int: ...
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx:builtins.int) -> Instr: ...
    def pythonize(self) -> typing.Any:
        r"""
        Converts this identity to a Python-serializable form.
        """

@typing.final
class IdentityProver:
    r"""
    Rule-based prover for circuit identities.
    
    The prover is built from ECCs, extracts assumed rules, and can then:
    - check whether a target identity is derivable,
    - produce visited states for diagnostics,
    - export explicit proof traces.
    """
    @staticmethod
    def build_from_eccs(eccs:ECCs) -> IdentityProver:
        r"""
        Python entrypoint: builds a prover from generated ECCs.
        """
    def par_apply_rules(self, identity:IdentityCirc, additional_size:builtins.int) -> builtins.list[IdentityCirc]:
        r"""
        Applies one round of parallel rule rewriting bounded by `additional_size`.
        """
    def add_identity(self, identity:IdentityCirc, additional_size:builtins.int, count_limit:builtins.int) -> builtins.bool:
        r"""
        Inserts one identity into the prover, deriving it when possible.
        
        Returns `true` when this identity must be kept as an assumption.
        """
    def add_identity_search(self, identity:IdentityCirc, additional_size:builtins.int, count_limit:builtins.int) -> tuple[builtins.set[IdentityCirc], builtins.bool]:
        r"""
        Internal bounded search used by [`Self::add_identity`].
        
        Returns `(visited, assumed)` where `assumed=true` means the identity
        could not be derived within `count_limit`.
        """
    def prove_identity(self, identity:IdentityCirc, additional_size:builtins.int, count_limit:builtins.int) -> typing.Optional[IdentityCirc]:
        r"""
        Attempts to prove one identity.
        
        Returns `None` if proved, or `Some(identity)` if the search exceeded limits.
        """
    def prove_identity_with_visited(self, identity:IdentityCirc, additional_size:builtins.int, count_limit:builtins.int) -> tuple[typing.Optional[IdentityCirc], builtins.set[IdentityCirc]]:
        r"""
        Same as [`Self::prove_identity`] but also returns visited identities.
        """
    def export_proof(self, identity:IdentityCirc, additional_size:builtins.int, count_limit:builtins.int) -> typing.Optional[Proof]:
        r"""
        Exports a proof DAG when `identity` is derivable under the given limits.
        """
    def get_assumed(self) -> builtins.list[IdentityCirc]:
        r"""
        Returns current assumptions as a cloned list (Python helper).
        """
    @staticmethod
    def from_postcard(filepath:builtins.str) -> IdentityProver:
        r"""
        Loads a prover from postcard serialization.
        """
    def dump_postcard(self, filepath:builtins.str) -> None:
        r"""
        Stores a prover as postcard serialization.
        """

@typing.final
class Instr:
    r"""
    A compact, index-only quantum instruction used internally by the search/prover.
    """
    @property
    def gate(self) -> Gate:
        r"""
        Underlying gate.
        """
    @property
    def qargs(self) -> builtins.list[builtins.int]:
        r"""
        Qubit arguments as dense integer indices.
        """
    def __new__(cls, gate:Gate, qargs:typing.Sequence[builtins.int]) -> Instr:
        r"""
        Creates a compact instruction from a gate and integer qubit arguments.
        """
    def apply_permutation(self, perm:builtins.list[builtins.int]) -> Instr:
        r"""
        Applies a qubit permutation.
        """
    def arg_mask(self) -> builtins.int:
        r"""
        Bitmask of qubits touched by this instruction.
        """
    def pass_mask(self, mask:builtins.int) -> typing.Optional[builtins.int]:
        r"""
        Updates a frontier mask for left-to-right scheduling checks.
        """
    def largest_qubit(self) -> builtins.int:
        r"""
        Largest qubit index touched by this instruction.
        """
    def permut(self, perm:builtins.list[builtins.int]) -> Instr:
        r"""
        Alias of `apply_permutation`.
        """
    def disjoint(self, other:Instr) -> builtins.bool:
        r"""
        Returns `true` when this and `other` touch disjoint qubits.
        """
    def adjoint(self) -> Instr:
        r"""
        Returns the adjoint instruction.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __hash__(self) -> builtins.int: ...
    def position_of_qubit(self, qubit:builtins.int) -> typing.Optional[builtins.int]:
        r"""
        Returns position of `qubit` in argument list, if present.
        """

@typing.final
class Instruction:
    r"""
    A high-level instruction with gate + explicit quantum/classical register arguments.
    """
    @property
    def gate(self) -> Gate: ...
    @gate.setter
    def gate(self, value: Gate) -> None: ...
    @property
    def qargs(self) -> builtins.list[Argument]: ...
    @qargs.setter
    def qargs(self, value: builtins.list[Argument]) -> None: ...
    @property
    def cargs(self) -> builtins.list[Argument]: ...
    @cargs.setter
    def cargs(self, value: builtins.list[Argument]) -> None: ...
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def __new__(cls, gate:Gate, qargs:typing.Sequence[typing.Union[Argument, tuple[builtins.str, builtins.int]]], cargs:typing.Sequence[typing.Union[Argument, tuple[builtins.str, builtins.int]]]=[]) -> Instruction:
        r"""
        Creates a high-level instruction with explicit quantum/classical arguments.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class OrderInfo:
    r"""
    Ordering/equality-class information for qubit symmetry handling.
    """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def __new__(cls, size:builtins.int) -> OrderInfo:
        r"""
        Creates a single-class ordering of `size` qubits.
        """
    def n_eqclasses(self) -> builtins.int:
        r"""
        Number of current equality classes.
        """
    def has_eq(self) -> builtins.bool:
        r"""
        Returns true if any equality class has size > 1.
        """
    def first_eqclass(self) -> typing.Optional[builtins.int]:
        r"""
        Index of first non-trivial equality class.
        """
    def first_eqclass_after(self, idx:builtins.int) -> typing.Optional[builtins.int]:
        r"""
        Index of first non-trivial equality class at/after `idx`.
        """
    def as_bits(self) -> tuple[builtins.list[builtins.int], builtins.int]:
        r"""
        Returns canonical permutation and equality bitmask.
        """

@typing.final
class Proof:
    r"""
    Exported proof DAG.
    
    Each entry stores:
    - an identity circuit,
    - either `None` (assumption) or `(lhs_idx, rhs_idx)` showing how it is derived.
    """
    @property
    def raw(self) -> builtins.list[tuple[IdentityCirc, typing.Optional[tuple[builtins.int, builtins.int]]]]:
        r"""
        Returns raw proof entries.
        """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __lt__(self, other:builtins.object) -> builtins.bool: ...
    def __le__(self, other:builtins.object) -> builtins.bool: ...
    def __gt__(self, other:builtins.object) -> builtins.bool: ...
    def __ge__(self, other:builtins.object) -> builtins.bool: ...
    def __new__(cls, data:typing.Sequence[tuple[IdentityCirc, typing.Optional[tuple[builtins.int, builtins.int]]]]) -> Proof:
        r"""
        Creates a proof from raw `(identity, dependency)` entries.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class RawECCs:
    r"""
    Mutable ECC map keyed by evaluator hash.
    
    This is the direct output of the search algorithm before final simplification.
    """
    def __new__(cls, evaluator:Evaluator) -> RawECCs:
        r"""
        Initializes the raw map with the empty circuit class.
        """
    @staticmethod
    def search_naive(evaluator:Evaluator, instrs:typing.Sequence[Instr], max_size:builtins.int) -> tuple[RawECCs, builtins.list[builtins.int]]:
        r"""
        Exhaustive baseline search without permutation-based multiplicity reduction.
        """
    @staticmethod
    def search(evaluator:Evaluator, instrs:typing.Sequence[Instr], max_size:builtins.int) -> tuple[RawECCs, builtins.list[builtins.int]]:
        r"""
        Optimized search using permutation-equivalent placements per circuit.
        """
    def simplify(self) -> ECCs:
        r"""
        Converts raw buckets into sorted, normalized ECCs.
        """
    @staticmethod
    def generate(evaluator:Evaluator, gates:typing.Sequence[Gate], max_size:builtins.int) -> tuple[RawECCs, builtins.list[builtins.int]]:
        r"""
        Generates ECCs from a gate set using the optimized search.
        
        Adjoint gates are added automatically if missing.
        """
    @staticmethod
    def generate_naive(evaluator:Evaluator, gates:typing.Sequence[Gate], max_size:builtins.int) -> tuple[RawECCs, builtins.list[builtins.int]]:
        r"""
        Generates ECCs from a gate set using the naive search.
        """
    def find_equivalents(self, evaluator:Evaluator, instrs:typing.Sequence[Instr]) -> typing.Optional[ECC]:
        r"""
        Python wrapper returning equivalent circuits for a candidate program.
        """
    def compute_next_key(self, evaluator:Evaluator, current_key:builtins.int, instr:Instr) -> typing.Optional[builtins.int]:
        r"""
        Computes the next reachable ECC hash after appending one instruction.
        
        Returns `None` when the resulting state was not discovered in this map.
        """
    def switch_evaluator(self, new_evaluator:Evaluator) -> RawECCs:
        r"""
        Re-evaluates all stored circuits under a new evaluator.
        
        Useful for cross-checking evaluator-independence of discovered classes.
        """
    def check_identity_subset(self, ecc1:RawECCs, evaluator:Evaluator) -> None:
        r"""
        Checks that every identity in `self` is representable in `ecc1`.
        """

@typing.final
class StateVec:
    r"""
    Complex state vector used for randomized circuit evaluation.
    """
    def __eq__(self, other:builtins.object) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def __new__(cls, re:typing.Sequence[builtins.float], im:typing.Sequence[builtins.float]) -> StateVec:
        r"""
        Creates a state vector from real/imaginary coefficient arrays.
        """
    def hash_value(self) -> builtins.int:
        r"""
        Hashes the current normalized state.
        """
    @staticmethod
    def random(num_qubits:builtins.int) -> StateVec:
        r"""
        Creates a random normalized state.
        """
    @staticmethod
    def random_symmetric(num_qubits:builtins.int) -> StateVec:
        r"""
        Creates a random state tailored for symmetry-aware evaluator use.
        """
    def nqubits(self) -> builtins.int:
        r"""
        Returns qubit count.
        """
    def len(self) -> builtins.int:
        r"""
        Returns vector length (`2^nqubits`).
        """
    def normalize(self) -> None:
        r"""
        Normalizes the state vector in place.
        
        Normalization ensures two conditions:
        1. Amplitude Normalization: The sum of the squares of the absolute values of
           the complex amplitudes is 1 (i.e., `sum(|psi_i|^2) = 1`).
        2. Phase Normalization: The first non-zero element of the state vector
           is made real and positive.
        
        If the vector is effectively all zeros initially (all amplitudes are very close to zero),
        it is normalized to the |0...0> state (i.e., the first element becomes 1.0 + 0.0i,
        and all other elements become 0.0 + 0.0i).
        If the vector has zero length, this function does nothing.
        """
    def normalize_arg(self) -> None:
        r"""
        Canonicalizes global phase for stable equality/hash comparison.
        """
    def __getitem__(self, index:builtins.int) -> builtins.complex:
        r"""
        Returns one amplitude as Python `complex`.
        """
    def __setitem__(self, index:builtins.int, value:builtins.complex) -> None:
        r"""
        Sets one amplitude from Python `complex`.
        """
    def __imul__(self, slf:StateVec, other:Instr) -> None:
        r"""
        In-place application of one instruction.
        """
    def clone(self) -> StateVec:
        r"""
        Returns a deep copy.
        """
    def check(self) -> builtins.bool:
        r"""
        Checks unit-norm invariant.
        """

